/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[3];
new Text:FuelLunar;
new Text:NameSpeedo;
new PlayerText:HealthLunar[MAX_PLAYERS];
new PlayerText:SpeedoLunar[MAX_PLAYERS];

//Textdraws
PublicTD[0] = TextDrawCreate(526.000000, 411.000000, "ld_drv:blkdot");
TextDrawFont(PublicTD[0], 4);
TextDrawLetterSize(PublicTD[0], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[0], 86.500000, 14.500000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 1);
TextDrawColor(PublicTD[0], 255);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 50);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(528.000000, 412.000000, "ld_drv:blkdot");
TextDrawFont(PublicTD[1], 4);
TextDrawLetterSize(PublicTD[1], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[1], 83.500000, 11.500000);
TextDrawSetOutline(PublicTD[1], 1);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], 1296911871);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 1);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

FuelLunar = TextDrawCreate(564.000000, 384.000000, "10 L");
TextDrawFont(FuelLunar, 3);
TextDrawLetterSize(FuelLunar, 0.162496, 1.200000);
TextDrawTextSize(FuelLunar, 405.500000, 17.000000);
TextDrawSetOutline(FuelLunar, 1);
TextDrawSetShadow(FuelLunar, 1);
TextDrawAlignment(FuelLunar, 2);
TextDrawColor(FuelLunar, -65281);
TextDrawBackgroundColor(FuelLunar, 255);
TextDrawBoxColor(FuelLunar, 50);
TextDrawUseBox(FuelLunar, 0);
TextDrawSetProportional(FuelLunar, 1);
TextDrawSetSelectable(FuelLunar, 0);

PublicTD[2] = TextDrawCreate(566.000000, 398.000000, "mp/h");
TextDrawFont(PublicTD[2], 3);
TextDrawLetterSize(PublicTD[2], 0.162496, 1.200000);
TextDrawTextSize(PublicTD[2], 405.500000, 17.000000);
TextDrawSetOutline(PublicTD[2], 1);
TextDrawSetShadow(PublicTD[2], 1);
TextDrawAlignment(PublicTD[2], 2);
TextDrawColor(PublicTD[2], -1);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], 50);
TextDrawUseBox(PublicTD[2], 0);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);

NameSpeedo = TextDrawCreate(542.000000, 369.000000, "kontol");
TextDrawFont(NameSpeedo, 3);
TextDrawLetterSize(NameSpeedo, 0.245829, 1.649999);
TextDrawTextSize(NameSpeedo, 405.500000, 17.000000);
TextDrawSetOutline(NameSpeedo, 1);
TextDrawSetShadow(NameSpeedo, 1);
TextDrawAlignment(NameSpeedo, 2);
TextDrawColor(NameSpeedo, 1097458175);
TextDrawBackgroundColor(NameSpeedo, 255);
TextDrawBoxColor(NameSpeedo, 50);
TextDrawUseBox(NameSpeedo, 0);
TextDrawSetProportional(NameSpeedo, 1);
TextDrawSetSelectable(NameSpeedo, 0);


//Player Textdraws
HealthLunar[playerid] = CreatePlayerTextDraw(playerid, 528.000000, 412.000000, "ld_drv:blkdot");
PlayerTextDrawFont(playerid, HealthLunar[playerid], 4);
PlayerTextDrawLetterSize(playerid, HealthLunar[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HealthLunar[playerid], 83.500000, 11.500000);
PlayerTextDrawSetOutline(playerid, HealthLunar[playerid], 1);
PlayerTextDrawSetShadow(playerid, HealthLunar[playerid], 0);
PlayerTextDrawAlignment(playerid, HealthLunar[playerid], 1);
PlayerTextDrawColor(playerid, HealthLunar[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, HealthLunar[playerid], 255);
PlayerTextDrawBoxColor(playerid, HealthLunar[playerid], 50);
PlayerTextDrawUseBox(playerid, HealthLunar[playerid], 1);
PlayerTextDrawSetProportional(playerid, HealthLunar[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HealthLunar[playerid], 0);

SpeedoLunar[playerid] = CreatePlayerTextDraw(playerid, 542.000000, 379.000000, "000");
PlayerTextDrawFont(playerid, SpeedoLunar[playerid], 3);
PlayerTextDrawLetterSize(playerid, SpeedoLunar[playerid], 0.458332, 3.699995);
PlayerTextDrawTextSize(playerid, SpeedoLunar[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, SpeedoLunar[playerid], 1);
PlayerTextDrawSetShadow(playerid, SpeedoLunar[playerid], 1);
PlayerTextDrawAlignment(playerid, SpeedoLunar[playerid], 2);
PlayerTextDrawColor(playerid, SpeedoLunar[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, SpeedoLunar[playerid], 255);
PlayerTextDrawBoxColor(playerid, SpeedoLunar[playerid], 50);
PlayerTextDrawUseBox(playerid, SpeedoLunar[playerid], 0);
PlayerTextDrawSetProportional(playerid, SpeedoLunar[playerid], 1);
PlayerTextDrawSetSelectable(playerid, SpeedoLunar[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
