/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][6];
new PlayerText:VehNameRdl[MAX_PLAYERS];
new PlayerText:FuelRdl[MAX_PLAYERS];
new PlayerText:HealthRdl[MAX_PLAYERS];
new PlayerText:EngneRdl[MAX_PLAYERS];
new PlayerText:LockRdl[MAX_PLAYERS];
new PlayerText:TrunkRdl[MAX_PLAYERS];
new PlayerText:HoodRdl[MAX_PLAYERS];
new PlayerText:CloseVehRdl[MAX_PLAYERS];

//Textdraws

//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 321.000000, 259.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.612500, 13.650004);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 347.500000, 130.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 150);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 254.000000, 327.000000, "TextDraw");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 5);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 69.000000, 56.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 47);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][1], 451);
PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][1], -32.000000, 5.000000, -30.000000, 0.860000);
PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][1], 1, 1);

VehNameRdl[playerid] = CreatePlayerTextDraw(playerid, 355.000000, 370.000000, "Turismo");
PlayerTextDrawFont(playerid, VehNameRdl[playerid], 2);
PlayerTextDrawLetterSize(playerid, VehNameRdl[playerid], 0.295832, 1.299998);
PlayerTextDrawTextSize(playerid, VehNameRdl[playerid], 405.000000, 60.500000);
PlayerTextDrawSetOutline(playerid, VehNameRdl[playerid], 1);
PlayerTextDrawSetShadow(playerid, VehNameRdl[playerid], 0);
PlayerTextDrawAlignment(playerid, VehNameRdl[playerid], 2);
PlayerTextDrawColor(playerid, VehNameRdl[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, VehNameRdl[playerid], 255);
PlayerTextDrawBoxColor(playerid, VehNameRdl[playerid], 83);
PlayerTextDrawUseBox(playerid, VehNameRdl[playerid], 1);
PlayerTextDrawSetProportional(playerid, VehNameRdl[playerid], 1);
PlayerTextDrawSetSelectable(playerid, VehNameRdl[playerid], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 289.000000, 258.000000, "Health:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.166666, 1.299998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 405.000000, 65.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -16776961);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 83);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 289.000000, 275.000000, "Fuel:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.166666, 1.299998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 405.000000, 65.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], 16777215);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 83);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

FuelRdl[playerid] = CreatePlayerTextDraw(playerid, 310.000000, 275.000000, "10L");
PlayerTextDrawFont(playerid, FuelRdl[playerid], 2);
PlayerTextDrawLetterSize(playerid, FuelRdl[playerid], 0.166666, 1.299998);
PlayerTextDrawTextSize(playerid, FuelRdl[playerid], 405.000000, 65.500000);
PlayerTextDrawSetOutline(playerid, FuelRdl[playerid], 1);
PlayerTextDrawSetShadow(playerid, FuelRdl[playerid], 0);
PlayerTextDrawAlignment(playerid, FuelRdl[playerid], 2);
PlayerTextDrawColor(playerid, FuelRdl[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, FuelRdl[playerid], 255);
PlayerTextDrawBoxColor(playerid, FuelRdl[playerid], 83);
PlayerTextDrawUseBox(playerid, FuelRdl[playerid], 0);
PlayerTextDrawSetProportional(playerid, FuelRdl[playerid], 1);
PlayerTextDrawSetSelectable(playerid, FuelRdl[playerid], 0);

HealthRdl[playerid] = CreatePlayerTextDraw(playerid, 314.000000, 258.000000, "100%");
PlayerTextDrawFont(playerid, HealthRdl[playerid], 2);
PlayerTextDrawLetterSize(playerid, HealthRdl[playerid], 0.166666, 1.299998);
PlayerTextDrawTextSize(playerid, HealthRdl[playerid], 405.000000, 65.500000);
PlayerTextDrawSetOutline(playerid, HealthRdl[playerid], 1);
PlayerTextDrawSetShadow(playerid, HealthRdl[playerid], 0);
PlayerTextDrawAlignment(playerid, HealthRdl[playerid], 2);
PlayerTextDrawColor(playerid, HealthRdl[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, HealthRdl[playerid], 255);
PlayerTextDrawBoxColor(playerid, HealthRdl[playerid], 83);
PlayerTextDrawUseBox(playerid, HealthRdl[playerid], 0);
PlayerTextDrawSetProportional(playerid, HealthRdl[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HealthRdl[playerid], 0);

EngneRdl[playerid] = CreatePlayerTextDraw(playerid, 424.000000, 259.000000, "Engine");
PlayerTextDrawFont(playerid, EngneRdl[playerid], 2);
PlayerTextDrawLetterSize(playerid, EngneRdl[playerid], 0.166666, 1.299998);
PlayerTextDrawTextSize(playerid, EngneRdl[playerid], 405.000000, 65.500000);
PlayerTextDrawSetOutline(playerid, EngneRdl[playerid], 1);
PlayerTextDrawSetShadow(playerid, EngneRdl[playerid], 0);
PlayerTextDrawAlignment(playerid, EngneRdl[playerid], 2);
PlayerTextDrawColor(playerid, EngneRdl[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, EngneRdl[playerid], 255);
PlayerTextDrawBoxColor(playerid, EngneRdl[playerid], 180);
PlayerTextDrawUseBox(playerid, EngneRdl[playerid], 1);
PlayerTextDrawSetProportional(playerid, EngneRdl[playerid], 1);
PlayerTextDrawSetSelectable(playerid, EngneRdl[playerid], 1);

LockRdl[playerid] = CreatePlayerTextDraw(playerid, 424.000000, 278.000000, "Lock");
PlayerTextDrawFont(playerid, LockRdl[playerid], 2);
PlayerTextDrawLetterSize(playerid, LockRdl[playerid], 0.166666, 1.299998);
PlayerTextDrawTextSize(playerid, LockRdl[playerid], 405.000000, 65.500000);
PlayerTextDrawSetOutline(playerid, LockRdl[playerid], 1);
PlayerTextDrawSetShadow(playerid, LockRdl[playerid], 0);
PlayerTextDrawAlignment(playerid, LockRdl[playerid], 2);
PlayerTextDrawColor(playerid, LockRdl[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, LockRdl[playerid], 255);
PlayerTextDrawBoxColor(playerid, LockRdl[playerid], 180);
PlayerTextDrawUseBox(playerid, LockRdl[playerid], 1);
PlayerTextDrawSetProportional(playerid, LockRdl[playerid], 1);
PlayerTextDrawSetSelectable(playerid, LockRdl[playerid], 1);

TrunkRdl[playerid] = CreatePlayerTextDraw(playerid, 424.000000, 297.000000, "Trunk");
PlayerTextDrawFont(playerid, TrunkRdl[playerid], 2);
PlayerTextDrawLetterSize(playerid, TrunkRdl[playerid], 0.166666, 1.299998);
PlayerTextDrawTextSize(playerid, TrunkRdl[playerid], 405.000000, 65.500000);
PlayerTextDrawSetOutline(playerid, TrunkRdl[playerid], 1);
PlayerTextDrawSetShadow(playerid, TrunkRdl[playerid], 0);
PlayerTextDrawAlignment(playerid, TrunkRdl[playerid], 2);
PlayerTextDrawColor(playerid, TrunkRdl[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, TrunkRdl[playerid], 255);
PlayerTextDrawBoxColor(playerid, TrunkRdl[playerid], 180);
PlayerTextDrawUseBox(playerid, TrunkRdl[playerid], 1);
PlayerTextDrawSetProportional(playerid, TrunkRdl[playerid], 1);
PlayerTextDrawSetSelectable(playerid, TrunkRdl[playerid], 1);

HoodRdl[playerid] = CreatePlayerTextDraw(playerid, 424.000000, 316.000000, "Hood");
PlayerTextDrawFont(playerid, HoodRdl[playerid], 2);
PlayerTextDrawLetterSize(playerid, HoodRdl[playerid], 0.166666, 1.299998);
PlayerTextDrawTextSize(playerid, HoodRdl[playerid], 405.000000, 65.500000);
PlayerTextDrawSetOutline(playerid, HoodRdl[playerid], 1);
PlayerTextDrawSetShadow(playerid, HoodRdl[playerid], 0);
PlayerTextDrawAlignment(playerid, HoodRdl[playerid], 2);
PlayerTextDrawColor(playerid, HoodRdl[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, HoodRdl[playerid], 255);
PlayerTextDrawBoxColor(playerid, HoodRdl[playerid], 180);
PlayerTextDrawUseBox(playerid, HoodRdl[playerid], 1);
PlayerTextDrawSetProportional(playerid, HoodRdl[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HoodRdl[playerid], 1);

CloseVehRdl[playerid] = CreatePlayerTextDraw(playerid, 407.000000, 327.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, CloseVehRdl[playerid], 4);
PlayerTextDrawLetterSize(playerid, CloseVehRdl[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, CloseVehRdl[playerid], 30.000000, 29.500000);
PlayerTextDrawSetOutline(playerid, CloseVehRdl[playerid], 1);
PlayerTextDrawSetShadow(playerid, CloseVehRdl[playerid], 0);
PlayerTextDrawAlignment(playerid, CloseVehRdl[playerid], 1);
PlayerTextDrawColor(playerid, CloseVehRdl[playerid], 173);
PlayerTextDrawBackgroundColor(playerid, CloseVehRdl[playerid], 255);
PlayerTextDrawBoxColor(playerid, CloseVehRdl[playerid], 50);
PlayerTextDrawUseBox(playerid, CloseVehRdl[playerid], 1);
PlayerTextDrawSetProportional(playerid, CloseVehRdl[playerid], 1);
PlayerTextDrawSetSelectable(playerid, CloseVehRdl[playerid], 1);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 422.000000, 330.000000, "x");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 321.000000, 242.000000, "Vehicle Panel");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.166666, 1.299998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 452.000000, 130.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 1296911796);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
